# Generated by Django 2.1.11 on 2019-10-03 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodInMoodLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madeOn', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='MoodScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scaleName', models.CharField(max_length=30)),
                ('scaleType', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ScaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('alias', models.CharField(max_length=25)),
                ('moodScale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaleItems', to='moodapp.MoodScale')),
            ],
        ),
        migrations.AddField(
            model_name='moodinmoodlog',
            name='moodLog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moodInMoodLogs', to='moodapp.MoodLog'),
        ),
        migrations.AddField(
            model_name='moodinmoodlog',
            name='scaleItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moodInMoodLogs', to='moodapp.ScaleItem'),
        ),
        migrations.AlterUniqueTogether(
            name='scaleitem',
            unique_together={('moodScale', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='moodinmoodlog',
            unique_together={('moodLog', 'scaleItem')},
        ),
    ]
