# Generated by Django 2.1.11 on 2019-10-06 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moodLogs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodscale',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moodScales', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
