# Generated by Django 2.1.11 on 2019-10-09 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moodapp', '0002_auto_20191006_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaleitem',
            name='moodScale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scaleItems', to='moodapp.MoodScale'),
        ),
    ]
