# Generated by Django 2.1.11 on 2019-10-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moodapp', '0003_auto_20191009_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodlog',
            name='scaleItems',
            field=models.ManyToManyField(related_name='moodLogs', through='moodapp.MoodInMoodLog', to='moodapp.ScaleItem'),
        ),
        migrations.AlterField(
            model_name='scaleitem',
            name='moodScale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scaleItems', to='moodapp.MoodScale'),
            preserve_default=False,
        ),
    ]
